# Generated by Django 5.2.2 on 2025-06-09 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_rename_user_organisation_owner'),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.organisation'),
        ),
    ]
