# Generated by Django 5.2.2 on 2025-06-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_alter_driver_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='address',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
