# Generated by Django 5.2.2 on 2025-06-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_alter_driver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='bank_account',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='ifsc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
