# Generated by Django 5.2.2 on 2025-06-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_driver_bank_account_driver_ifsc'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='beneficiary_id',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='bank_account',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='ifsc',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
