# Generated by Django 5.2.2 on 2025-06-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_alter_organisation_organisation_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='user',
            new_name='owner',
        ),
    ]
