# Generated by Django 5.2.2 on 2025-06-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_rename_user_organisation_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='owner',
        ),
    ]
