# Generated by Django 5.2.2 on 2025-06-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_remove_organisation_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='address',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
