# Generated by Django 5.2.2 on 2025-06-11 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='cabbie',
            new_name='driver',
        ),
    ]
