# Generated by Django 5.2.2 on 2025-06-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='driver',
        ),
    ]
