# Generated by Django 5.2.2 on 2025-06-08 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_remove_group_driver'),
        ('organisation', '0002_alter_organisation_organisation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='group',
            name='monthly_rental',
        ),
        migrations.AlterField(
            model_name='group',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_group', to='organisation.organisation'),
        ),
    ]
