# Generated by Django 5.2.2 on 2025-06-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_group'),
        ('group', '0003_remove_group_employees_remove_group_monthly_rental_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='employees',
            field=models.ManyToManyField(related_name='groups', to='employee.employee'),
        ),
    ]
