# Generated by Django 5.2.2 on 2025-06-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_group_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='employees',
        ),
    ]
