# Generated by Django 5.2.2 on 2025-06-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_grouphistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouphistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
