# Generated by Django 5.2.2 on 2025-06-16 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_alter_grouphistory_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupHistory',
        ),
    ]
