# Generated by Django 5.2.2 on 2025-06-08 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('group', '0002_remove_group_driver'),
        ('organisation', '0002_alter_organisation_organisation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_employees', to='group.group'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_employee', to='organisation.organisation'),
        ),
    ]
