# Generated by Django 5.2.2 on 2025-06-08 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_group_alter_employee_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='group',
        ),
    ]
