# Generated by Django 5.2.2 on 2025-06-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
