# Generated by Django 5.2.2 on 2025-06-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_employee_group_groupempoyeemapping_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupempoyeemapping',
            old_name='is_active',
            new_name='is_active_member',
        ),
    ]
