# Generated by Django 5.2.2 on 2025-06-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_rename_groupempoyeemapping_groupemployeemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='group',
            field=models.ManyToManyField(related_name='employees', through='employee.GroupEmployeeMapping', to='employee.employee'),
        ),
    ]
