# Generated by Django 5.2.2 on 2025-06-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_employee_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='group',
            new_name='groups',
        ),
    ]
