# Generated by Django 5.2.2 on 2025-06-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_alter_employee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='id',
            new_name='employee_id',
        ),
    ]
