# Generated by Django 5.2.2 on 2025-06-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_rename_id_employee_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_id',
            new_name='id',
        ),
    ]
