# Generated by Django 5.2.2 on 2025-06-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_employee_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='shift_timings',
            field=models.CharField(blank=True, default='9am-6pm', max_length=50, null=True),
        ),
    ]
