# Generated by Django 5.2.2 on 2025-07-02 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_alter_employee_shift_timings'),
        ('group', '0008_delete_grouphistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='groups',
        ),
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.group'),
        ),
        migrations.DeleteModel(
            name='GroupEmployeeMapping',
        ),
    ]
