# Generated by Django 5.2.2 on 2025-06-17 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('offer', '0002_rename_cabbie_offer_driver'),
        ('tendor', '0010_alter_grouphistory_tender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer', to='offer.offer'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tender', to='tendor.tender'),
        ),
    ]
