# Generated by Django 5.2.2 on 2025-06-05 09:29

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monthly_rental', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('location_details', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default='list', size=None)),
                ('drop_timings', models.TimeField()),
                ('pickup_timings', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='group.group')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_tendor', to='organisation.organisation')),
            ],
        ),
    ]
