# Generated by Django 5.2.2 on 2025-06-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendor', '0002_remove_tender_drop_timings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='drop_location',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='monthly_rental',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='pickup_location',
        ),
        migrations.AddField(
            model_name='tender',
            name='group_size',
            field=models.IntegerField(default=4),
        ),
    ]
