# Generated by Django 5.2.2 on 2025-06-10 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendor', '0003_remove_tender_drop_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='drop_timing',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='tender',
            name='pickup_timing',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
    ]
