# Generated by Django 5.2.2 on 2025-06-11 04:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendor', '0004_tender_drop_timing_tender_pickup_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='company_share',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='tender',
            name='pending_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tender',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
