# Generated by Django 5.2.2 on 2025-06-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendor', '0005_tender_company_share_tender_pending_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
