# Generated by Django 5.2.2 on 2025-06-12 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendor', '0006_tender_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tender_travel_details', models.JSONField(blank=True, null=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tendor.tender')),
            ],
        ),
    ]
