# Generated by Django 5.2.2 on 2025-06-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendor', '0007_tenderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='monthly_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tenderhistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
