# Generated by Django 5.2.2 on 2025-06-16 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendor', '0008_tender_monthly_charges_alter_tenderhistory_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('group_history', models.JSONField(blank=True, null=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tendor.tender')),
            ],
        ),
    ]
