# Generated by Django 5.2.2 on 2025-06-16 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendor', '0009_grouphistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouphistory',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tendor.tender'),
        ),
    ]
