# Generated by Django 5.2.2 on 2025-06-18 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_alter_driver_address'),
        ('employee', '0012_rename_group_employee_groups'),
        ('tendor', '0010_alter_grouphistory_tender'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderTravelDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tendor.tender')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTravelDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_timing', models.DateTimeField(blank=True, null=True)),
                ('drop_timing', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('tender_travel_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tendor.tendertraveldetails')),
            ],
        ),
        migrations.CreateModel(
            name='DriverTravelDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picked_employees', models.BooleanField(default=False)),
                ('droped_employees', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
                ('tender_travel_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tendor.tendertraveldetails')),
            ],
        ),
        migrations.DeleteModel(
            name='TenderHistory',
        ),
    ]
