# Generated by Django 5.2.2 on 2025-06-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendor', '0011_tendertraveldetails_employeetraveldetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
