# Generated by Django 5.2.2 on 2025-06-23 11:21

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_alter_driver_user'),
        ('employee', '0016_employee_is_deleted'),
        ('tendor', '0012_tender_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tendertraveldetails',
            name='tender',
        ),
        migrations.RemoveField(
            model_name='employeetraveldetails',
            name='tender_travel_detail',
        ),
        migrations.RemoveField(
            model_name='drivertraveldetails',
            name='tender_travel_detail',
        ),
        migrations.AddField(
            model_name='drivertraveldetails',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='drivertraveldetails',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tendor.tender'),
        ),
        migrations.AddField(
            model_name='employeetraveldetails',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employeetraveldetails',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tendor.tender'),
        ),
        migrations.AddField(
            model_name='tender',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 23, 11, 21, 6, 436780, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='drivertraveldetails',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.driver'),
        ),
        migrations.AlterField(
            model_name='employeetraveldetails',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.CreateModel(
            name='EmployeeTenderHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leaving_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('amount_paid', models.IntegerField(default=0)),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tendor.tender')),
            ],
        ),
        migrations.DeleteModel(
            name='GroupHistory',
        ),
        migrations.DeleteModel(
            name='TenderTravelDetails',
        ),
    ]
