# Generated by Django 5.2.2 on 2025-06-23 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendor', '0013_remove_tendertraveldetails_tender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivertraveldetails',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employeetenderhistory',
            name='leaving_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeetraveldetails',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 23, 11, 21, 41, 494858, tzinfo=datetime.timezone.utc)),
        ),
    ]
