# Generated by Django 5.2.2 on 2025-06-24 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendor', '0014_alter_drivertraveldetails_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 24, 5, 37, 26, 967725, tzinfo=datetime.timezone.utc)),
        ),
    ]
