# Generated by Django 5.2.2 on 2025-06-26 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendor', '0015_alter_tender_expire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='description',
        ),
        migrations.AlterField(
            model_name='tender',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 9, 40, 15, 809124, tzinfo=datetime.timezone.utc)),
        ),
    ]
