# Generated by Django 5.2.2 on 2025-06-26 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendor', '0016_remove_tender_description_alter_tender_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 11, 40, 35, 627753, tzinfo=datetime.timezone.utc)),
        ),
    ]
