# Generated by Django 5.2.2 on 2025-07-02 03:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_remove_employee_groups_employee_group_and_more'),
        ('tendor', '0018_alter_tender_expire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='group',
        ),
        migrations.AddField(
            model_name='employeetenderhistory',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='employeetenderhistory',
            name='is_active_member',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='employees',
            field=models.ManyToManyField(through='tendor.EmployeeTenderHistory', to='tendor.tender'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 1, 3, 27, 38, 74955, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tender',
            name='group_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
